---
title: "Process fish surveys"
author: "Juan Mayorga"
number-sections: true
date: "03/26/2024"
format: 
  html:
    self-contained: true
    code-fold: true
    toc: true
    toc-location: left
---

```{r, message=F, warning = F, fig.width=10, fig.height=10}
library(ggtext)
library(paletteer)
library(sf)
library(terra)
library(tidyverse)
library(gt)
library(DBI)
library(bigrquery)

knitr::opts_chunk$set(eval = T, warning = F, message = F, include = T, echo = F)

PristineSeasR::set_ps_paths(email = "marine.data.science@ngs.org")

exp_path <- file.path(ps_science_path, "expeditions", "Niue-2023")

ps_data_path <- file.path(ps_science_path, "datasets/")

bq_auth(email = "marine.data.science@ngs.org")

bq_connection <- dbConnect(bigquery(), 
                           project = "pristine-seas")
```

# Metadata

```{r eval = T}
fish_meta <- tbl(bq_connection, "metadata.NIU_2023_fish") |> 
  arrange(ps_station_id) |>
  collect()

fish_meta |> 
  group_by(location, habitat, exposure) |> 
  summarize(n_stations = n_distinct(ps_station_id),
            n_strata = n_distinct(depth_strata),
            n_transects = sum(n_transects)) |> 
  ungroup() |>
  group_by(location) |> 
  gt() |> 
  tab_header(title = "Number of stations per region, habitat, and exposure") 
```

```{r}
library(leaflet)

pal <- colorFactor(as.character(paletteer_d("ggthemes::few_Medium",9 )),
                   domain = unique(fish_meta$habitat))

fish_meta |> 
  filter(!is.na(lon)) |> 
  distinct(ps_station_id, lat, lon, habitat) %>% 
  leaflet() %>%
  addTiles() %>%
  setView(-169, -19, zoom = 8) %>%
  addCircleMarkers(label = ~habitat, 
                   color = ~pal(habitat), 
                   radius = 7, fillOpacity = 0.6, stroke = F, 
                   group = ~habitat) |> 
  addLayersControl(overlayGroups = ~habitat, 
                   options = layersControlOptions(collapsed = FALSE))
```

# Data processsing 

## Observations

```{r, eval = F}
fish_obs_JSM <- readxl::read_xlsx(file.path(exp_path,"data/primary/raw/fish",
                                            "NIU_2023_uvs_fish_fieldbook_JSM.xlsx"),
                                  sheet = "fish_obs")

fish_obs_AMF <- readxl::read_xlsx(file.path(exp_path,"data/primary/raw/fish"
                                            , "NIU_2023_uvs_fish_fieldbook_AMF.xlsx"),
                                  sheet = "fish_obs")

fish_obs <- bind_rows(fish_obs_AMF, fish_obs_JSM) |> 
  mutate(depth_strata = case_when(depth_m <= 5 ~ "Supershallow",
                                  depth_m <= 15 ~ "Shallow",
                                  depth_m > 15 ~ "Deep"),
         ps_station_id = str_replace(ps_site_id, "uvs", "2023_fish"),
         min_tl_cm = coalesce(min_tl_cm, max_tl_cm),
         avg_tl_cm = (min_tl_cm + max_tl_cm)/2) |> 
  filter(!is.na(taxon_code)) |> 
  select(ps_station_id, everything(), -terminal_phase, -notes,  -ps_site_id)
```

## Clean taxa

```{r worms, eval = F}
fish_lut <- read_csv(file.path(exp_path,"data/primary/raw/fish", "fish_taxa_list.csv")) |> 
  distinct(taxon_code, taxon_valid_name)

fish_lut$taxon_valid_name[fish_lut$taxon_code == "PA.INSU"] <- "Parupeneus insularis"

fish_lut$taxon_valid_name[fish_lut$taxon_code == "CH.SORD"] <- "Chlorurus spilurus"

taxa_list <- fish_obs |> 
  distinct(taxon_code) |> 
  left_join(fish_lut) |> 
  distinct()

taxonomy_worms <- taxa_list$taxon_valid_name %>% 
  split(ceiling(seq_along(taxa_list$taxon_valid_name)/20)) %>% 
  furrr::future_map_dfr(worrms::wm_records_names) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(scientificname)) %>% 
  mutate(rank = str_to_lower(rank),
         taxon_id = if_else(!is.na(valid_aphia_id),
                              paste0("WORMS:", valid_aphia_id),
                              NA_character_)) %>% 
  select(taxon_clean = scientificname, status, taxon_valid_name = valid_name, taxon_rank = rank, taxon_id, taxon_authority = valid_authority, kingdom, phylum, class, order, family, genus) %>% 
  distinct()

duped_taxa_worms <- taxonomy_worms %>% 
  janitor::get_dupes(taxon_clean) 

deduped_taxa_worms <- duped_taxa_worms %>% 
  filter(status %in% c("accepted")) %>% 
  select(-dupe_count)

taxonomy_worms <- taxonomy_worms %>% 
  group_by(taxon_clean) %>% 
  filter(n() <= 1) %>% # remove duplicates
  bind_rows(deduped_taxa_worms) # add deduped

taxonomy_worms %>% 
  filter(taxon_valid_name != taxon_clean)

taxa_list <- taxa_list |> 
  rename(taxon_clean = taxon_valid_name) |> 
  left_join(taxonomy_worms)

taxa_list$taxon_clean[taxa_list$taxon_code == "CH.SORD"] <- "Chlorurus sordidus"
taxa_list$status[taxa_list$taxon_code == "CH.SORD"] <- "regional congener"
```

```{r, fishbase, eval = F}
fish_trophic_group <- read_csv(file.path(ps_science_path, 
                                  "expeditions", 
                                  "SLI-2023", 
                                  "data/primary/raw/fish/Pacific_Indian_LW_params_21Sept2021.csv")) |> 
  janitor::clean_names() |> 
  distinct(taxon_code = new_name, common_family, consumer, trophic, trophic_detailed)

taxa_list <- taxa_list |> 
  left_join(fish_trophic_group) 

taxa_list$common_family[taxa_list$taxon_code == "CH.BAMI"] <- "Damselfish"
taxa_list$trophic[taxa_list$taxon_code == "CH.BAMI"] <- "Planktivore"
taxa_list$common_family[taxa_list$taxon_code == "SC.LONG"] <- "Parrotfish"
taxa_list$trophic[taxa_list$taxon_code == "SC.LONG"] <- "Herbivores"
taxa_list$common_family[taxa_list$taxon_code == "CI.ALBO"] <- "Hawkfish"
taxa_list$trophic[taxa_list$taxon_code == "CI.ALBO"] <- "Lower-carnivores"
taxa_list$taxon_valid_name[taxa_list$taxon_code == "PS.LORI"] <- "Pyronotanthias lori"
taxa_list$common_family[taxa_list$taxon_code == "PS.LORI"] <- "Anthias"
taxa_list$trophic[taxa_list$taxon_code == "PS.LORI"] <- "Planktivore"
taxa_list$common_family[taxa_list$taxon_code == "CH.TRIF"] <- "Butterflyfish"
taxa_list$trophic[taxa_list$taxon_code == "CH.TRIF"] <- "Lower-carnivores"
taxa_list$common_family[taxa_list$taxon_code == "PO.SPIL"] <- "Damselfish"
taxa_list$trophic[taxa_list$taxon_code == "PO.SPIL"] <- "Lower-carnivores"

fishbase_params <- taxa_list %>% 
  pull(taxon_valid_name) %>% 
  split(ceiling(seq_along(taxa_list$taxon_valid_name)/20)) %>% 
  furrr::future_map_dfr(rfishbase::estimate) %>% 
  janitor::clean_names() %>% 
  select(fb_taxa_code = spec_code, species, feeding_path, max_length_tl, troph, se_troph, a, sd_log10a, b,
         sd_b, method_ab, age_min, age_max) %>% 
  distinct()

taxa_list <- taxa_list |> 
  left_join(fishbase_params, 
            by = c("taxon_valid_name" = "species")) 

taxa_list |> 
  filter(is.na(a))

taxa_list$a[taxa_list$taxon_code == "PS.PASC"] <- 0.0123027
taxa_list$b[taxa_list$taxon_code == "PS.PASC"] <- 3
taxa_list$max_length_tl[taxa_list$taxon_code == "PS.PASC"] <- 20
```

```{r, size_outliers, eval = F}
fish_obs <- fish_obs |> 
  left_join(taxa_list |> 
              select(taxon_code, taxon_valid_name, a, b, max_length_tl)) 

fish_obs |> 
  filter(avg_tl_cm > max_length_tl) |> 
  mutate(diff = avg_tl_cm - max_length_tl) |> 
  filter(diff > 1) |> 
  arrange(desc(diff))
```

## Calculate biomass

```{r calc_biomass, eval = F}
biomass_by_obs <- fish_obs |> 
  mutate(avg_tl_cm = if_else(avg_tl_cm <= max_length_tl, avg_tl_cm, max_length_tl)) |> 
  mutate(biomass_gr = n_ind*a*(avg_tl_cm)^b,
         ind_m2 = if_else(avg_tl_cm <= 20, n_ind/50, n_ind/100),
         gr_m2 = if_else(avg_tl_cm <= 20, biomass_gr/50, biomass_gr/100)) |> 
  ungroup() |> 
  select(ps_station_id, diver, depth_strata, depth_m, transect, taxon_code, taxon_valid_name,  
         min_tl_cm, max_tl_cm, avg_tl_cm, n_ind, ind_m2, a, b, biomass_gr, gr_m2, -taxon_code) |> 
  mutate_if(is.numeric, round, 4)

biomass_by_transect <- biomass_by_obs |> 
  group_by(ps_station_id, depth_strata, depth_m, transect, diver, taxon_valid_name) |> 
  summarise(across(c("ind_m2",  "gr_m2"), sum, na.rm = T)) |> 
  pivot_wider(names_from = taxon_valid_name, 
              values_from = c(ind_m2,  gr_m2), 
              values_fill = 0, 
              names_sep = "-") |> 
  pivot_longer(cols = !c(ps_station_id, depth_strata, depth_m, transect, diver),
               names_to = c("variable","taxon_valid_name"), 
               names_sep = "-",
               values_to = "value") |> 
  pivot_wider(names_from = variable, values_from = value) |> 
  ungroup() |> 
  mutate_if(is.numeric, round, 4)

biomass_by_strata <- biomass_by_transect |> 
  group_by(ps_station_id, depth_strata, depth_m, diver, taxon_valid_name) |> 
  summarise(across(c("ind_m2",  "gr_m2"), mean, na.rm = T)) |> 
  ungroup() |> 
  mutate_if(is.numeric, round, 4)
```

## DB Upload

```{r bq_upload, eval = F}
bq_table_create("pristine-seas.fish_surveys.NIU_2023_taxa", 
                fields = as_bq_fields(taxa_list))

bigrquery::bq_table_upload("pristine-seas.fish_surveys.NIU_2023_taxa", 
                           values = taxa_list, fields = taxa_list)

bq_table_create("pristine-seas.fish_surveys.NIU_2023_biomass_by_obs", 
                fields = as_bq_fields(biomass_by_obs))

bigrquery::bq_table_upload("pristine-seas.fish_surveys.NIU_2023_biomass_by_obs", 
                           values = biomass_by_obs, fields = biomass_by_obs)

bq_table_create("pristine-seas.fish_surveys.NIU_2023_biomass_by_strata", 
                fields = as_bq_fields(biomass_by_strata))

bigrquery::bq_table_upload("pristine-seas.fish_surveys.NIU_2023_biomass_by_strata", 
                           values = biomass_by_strata, fields = biomass_by_strata)
```

# Analyses

```{r}
fish_meta <- tbl(bq_connection, "metadata.NIU_2023_fish") |> 
  arrange(ps_station_id) |>
  collect()

taxa_list <- tbl(bq_connection, 
                 "pristine-seas.fish_surveys.NIU_2023_taxa") |> 
  collect()

biomass_by_obs <- tbl(bq_connection, 
                      "pristine-seas.fish_surveys.NIU_2023_biomass_by_obs") |> 
  arrange(ps_station_id) |>
  collect()

biomass_by_strata <- tbl(bq_connection, 
                         "pristine-seas.fish_surveys.NIU_2023_biomass_by_strata") |> 
  arrange(ps_station_id) |>
  collect()
```

## By location

```{r}
summary_by_strata <- biomass_by_strata |> 
  group_by(ps_station_id, depth_strata, diver) |>
  summarize(n_taxa = n_distinct(taxon_valid_name[ind_m2 > 0]),
            ind_m2 = sum(ind_m2),
            gr_m2 = sum(gr_m2)) |> 
  left_join(fish_meta |> distinct(ps_station_id, location, exposure, habitat)) |> 
  ungroup()

summary_by_strata <- summary_by_strata |> 
  left_join(biomass_by_obs |> 
              group_by(ps_station_id, depth_strata, depth_m, diver) |> 
              summarize(n_transects = n_distinct(transect))) |> 
  select(ps_station_id, depth_strata, depth_m, diver, n_transects, everything())

summary_by_strata |> 
  group_by(location) |> 
  summarize(stations = n_distinct(ps_station_id[ind_m2 > 0]),
            transects = sum(n_transects),
            n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  mutate_if(is.numeric, round, 2) |> 
  gt() |> 
  opt_align_table_header(align = "left") |> 
  gt::tab_header(title = "Number of workstations and average species richness (# species/station-strata), fish abundance (ind/m2), and biomass (g/m2) for each location")
```

```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1

ggstatsplot::ggbetweenstats(data = summary_by_strata, x = location, y = n_taxa, 
                            type = "nonparametric",
                            title = "Species diversity by location", 
                            xlab = "")

ggstatsplot::ggbetweenstats(data = summary_by_strata, x = location, y = ind_m2, 
                            type = "nonparametric",
                            title = "Fish abundance by location", xlab = "")

ggstatsplot::ggbetweenstats(data = summary_by_strata, x = location, y = gr_m2, 
                            type = "nonparametric",
                            title = "Fish biomass by location", 
                            xlab = "")
```


## By depth strata

```{r}
summary_by_strata |> 
  group_by(location, depth_strata) |> 
  summarize(stations = n_distinct(ps_station_id[ind_m2 > 0]),
            transects = sum(n_transects),
            n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  mutate_if(is.numeric, round, 2) |> 
  ungroup() |> 
  gt(groupname_col = "location", rowname_col = "depth_strata") |> 
  tab_stubhead(label = "Location/Strata") |> 
  gt::tab_header(title = "Number of workstations and average species richness (# species/station-strata), fish abundance (ind/m2), and biomass (g/m2) for each location and depth strata") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(style = cell_text(align = "left", indent = px(20)),
    locations = cells_stub())
```

```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1
ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata |> 
                                      filter(location != "Antiope"), 
                                    x = depth_strata, y = n_taxa, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Richness (# species per station-strata)",
                                    annotation.args = list(title = "Fish species richness by depth strata"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata |> 
                                      filter(location != "Antiope"), 
                                    x = depth_strata, y = ind_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish abundance (ind/m2)",
                                    annotation.args = list(title = "Fish abundance by depth strata"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata |> 
                                      filter(location != "Antiope"), 
                                    x = depth_strata, y = gr_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish biomass (g/m2)",
                                    annotation.args = list(title = "Fish biomass by depth strata"))
```

## By exposure

```{r}
summary_by_strata |> 
  group_by(location, exposure) |> 
  summarize(stations = n_distinct(ps_station_id[ind_m2 > 0]),
            transects = sum(n_transects),
            n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  mutate_if(is.numeric, round, 2) |> 
  ungroup() |> 
  gt(groupname_col = "location", rowname_col = "exposure") |> 
  tab_stubhead(label = "Location/Strata") |> 
  gt::tab_header(title = "Number of workstations and average species richness (# species/station-strata), fish abundance (ind/m2), and biomass (g/m2) for each location and exposure") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(style = cell_text(align = "left", indent = px(20)),
    locations = cells_stub())
```


```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1
ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata|> 
                                      filter(location == "Beveridge"), 
                                    x = exposure, y = n_taxa, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Richness (# species per station-strata)",
                                    annotation.args = list(title = "Fish species richness by exposure"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata|> 
                                      filter(location == "Beveridge"), 
                                    x = exposure, y = ind_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish abundance (ind/m2)",
                                    annotation.args = list(title = "Fish abundance by exposure"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata|> 
                                      filter(location == "Beveridge"), 
                                    x = exposure, y = gr_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish biomass (g/m2)",
                                    annotation.args = list(title = "Fish biomass by exposure"))
```

## By habitat

```{r}
summary_by_strata |> 
  group_by(location, habitat) |> 
  summarize(stations = n_distinct(ps_station_id[ind_m2 > 0]),
            transects = sum(n_transects),
            n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  mutate_if(is.numeric, round, 2) |> 
  ungroup() |> 
  gt(groupname_col = "location", rowname_col = "habitat") |> 
  tab_stubhead(label = "Location/Strata") |> 
  gt::tab_header(title = "Number of workstations and average species richness (# species/station-strata), fish abundance (ind/m2), and biomass (g/m2) for each location and habitat") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(style = cell_text(align = "left", indent = px(20)),
    locations = cells_stub())
```

```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1
ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata|> 
                                      filter(location == "Beveridge"), 
                                    x = habitat, y = n_taxa, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Richness (# species per station-strata)",
                                    annotation.args = list(title = "Fish species richness by habitat"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata |> 
                                      filter(location == "Beveridge"), 
                                    x = habitat, y = ind_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish abundance (ind/m2)",
                                    annotation.args = list(title = "Fish abundance by habitat"))

ggstatsplot::grouped_ggbetweenstats(data = summary_by_strata |> 
                                      filter(location == "Beveridge"), 
                                    x = habitat, y = gr_m2, 
                                    grouping.var = location,
                                    type = "nonparametric", 
                                    p.adjust.method = "none",
                                    ylab = "Fish biomass (g/m2)",
                                    annotation.args = list(title = "Fish biomass by habitat"))
```

## Univariate adonis 

```{r}
fish_diversity_adonis <- vegan::adonis2(summary_by_strata %>% 
                                          select(n_taxa) ~  depth_strata + location  + exposure + habitat, 
                                        data = summary_by_strata,
                                        permutations = 1000,
                                        by = "margin",
                                        method = "euclidean")

broom::tidy(fish_diversity_adonis) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  ungroup() |> 
  gt(rowname_col = "term")  |> 
  gt::tab_header(title = "Results of Adonis model for univariate analysis of fish species richness") |> 
  opt_align_table_header(align = "left") 

fish_abundance_adonis <- vegan::adonis2(summary_by_strata %>% 
                                          select(ind_m2) ~  depth_strata + location  + exposure + habitat, 
                                        data = summary_by_strata,
                                        permutations = 1000,
                                        by = "margin",
                                        method = "euclidean")
broom::tidy(fish_abundance_adonis) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  ungroup() |> 
  gt(rowname_col = "term")  |> 
  gt::tab_header(title = "Results of Adonis model for univariate analysis of fish abundance") |> 
  opt_align_table_header(align = "left") 

fish_biomass_adonis <- vegan::adonis2(summary_by_strata %>% 
                                          select(gr_m2) ~  depth_strata + location  + exposure + habitat, 
                                        data = summary_by_strata,
                                        permutations = 1000,
                                        by = "margin",
                                        method = "euclidean")

broom::tidy(fish_biomass_adonis) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  ungroup() |> 
  gt(rowname_col = "term")  |> 
  gt::tab_header(title = "Results of Adonis model for univariate analysis of fish biomass") |> 
  opt_align_table_header(align = "left") 
```
## By family

```{r, fig.width=20, fig.height=10}
#| column: page
biomass_by_taxa <- biomass_by_obs |> 
  group_by(taxon_valid_name) |> 
  summarize(min_tl_cm = min(avg_tl_cm),
            mean_tl_cm = mean(avg_tl_cm),
            max_tl_cm = max(avg_tl_cm)) |> 
  left_join(biomass_by_strata |> 
              group_by(taxon_valid_name) |> 
              summarise(freq = 100*sum(ind_m2 > 0)/n(),
                        across(c("ind_m2",  "gr_m2"), mean, na.rm = T))) |> 
  mutate_if(is.numeric, round, 4) |> 
  left_join(taxa_list |> 
              select(taxon_valid_name, class, order, family, genus, common_family, trophic))

biomass_by_taxa |> 
  group_by(order, family) %>% 
  summarise(weight = n_distinct(taxon_valid_name)) %>% 
  ungroup() |> 
  ggplot(aes(area = weight, 
             label = paste(family, weight, sep = "\n"),
             fill = order,
             subgroup = order)) +
  treemapify::geom_treemap(show.legend = T)+
  treemapify::geom_treemap_text(colour = "black", place = "middle", reflow = T, min.size = 3)+
  labs(fill = "",
       title = "Number of fish species by family",
       subtitle = "Taxonomic order")+
  scale_fill_manual(values = paletteer_d("ggthemes::Tableau_20"))+
  bbplot::bbc_style()

ggsave(file.path(exp_path, "figures", "uvs_fish_taxa.pdf"), width = 20, height = 10)
```

```{r}
biomass_by_taxa |> 
  group_by(class, order, family) |> 
  summarize(n_genus = n_distinct(genus),
            n_species = n_distinct(taxon_valid_name),
            total_abundance = sum(ind_m2),
            total_biomass = sum(gr_m2)) |> 
  mutate_if(is.numeric, round, 3) |> 
  arrange(desc(total_biomass)) |> 
  gt(groupname_col = "class", rowname_col = "order") |> 
  tab_stubhead(label = "Class/Order") |> 
  gt::tab_header(title = "Number of families, species, total abundance (ind/m2) and biomass (g/m2) by taxonmic order") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(style = cell_text(align = "left", indent = px(20)),
            locations = cells_stub())
```

```{r}
summary_by_station_and_family <- biomass_by_strata |> 
  left_join(taxa_list |> distinct(taxon_valid_name, common_family)) |> 
  left_join(fish_meta |> distinct(ps_station_id, location, habitat, exposure)) |> 
  group_by(location,  habitat, common_family, ps_station_id, depth_strata, diver, exposure) |>
  summarize(gr_m2 = sum(gr_m2)) |> ungroup()

# generated from https://medialab.github.io/iwanthue/

fam_palette <- c("#62b3d2","#e4382c","#55c941","#683cd7","#9bbd3a","#c73fe1","#478731","#d155be","#6ac379","#5a359b","#d4b43c","#7b78db","#d78f3e","#5b7eb3","#d1602e","#5fc1aa","#dd3a7a","#407e63","#8c3077","#867e29","#544374","#aab074","#9a2a2b","#425324","#c998cb","#743c20","#c76a89","#9e6f49","#722f43","#db9b86","#e06364")
```

```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1
# exposure

tmp_df <- summary_by_station_and_family |> 
  mutate(island_exp = paste(location, exposure, sep = "-")) |> 
  #mutate(island_exp = if_else(location == "Beveridge", paste(location, exposure, sep = "-"), location)) |> 
  group_by(island_exp, common_family) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Family = ", common_family,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = common_family, tooltip = tooltip),
                                show.legend = T)+
  coord_flip()+
  labs(x = "", fill = "", title = "Fish biomass by location and exposure")+
  scale_fill_manual(values = rev(fam_palette))+
  ggthemes::theme_hc()+
    guides(fill = guide_legend(nrow = 5))+
  theme(legend.text = element_text(size = 6),
        legend.key.size = unit(.5, "lines"),
        legend.margin=margin(0,0,0,0))

ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_family_and_exposure.pdf"), width = 9)

# Habitat

tmp_df <- summary_by_station_and_family |> 
  mutate(island_exp = paste(location, habitat, sep = "-")) |> 
  group_by(island_exp, common_family) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Family = ", common_family,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = common_family, tooltip = tooltip),
                                show.legend = T)+
  coord_flip()+
  labs(x = "", fill = "", title = "Fish biomass by location and habitat")+
  scale_fill_manual(values = rev(fam_palette))+
  ggthemes::theme_hc()+
    guides(fill = guide_legend(nrow = 5))+
  theme(legend.text = element_text(size = 6),
        legend.key.size = unit(.5, "lines"),
        legend.margin=margin(0,0,0,0))


ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_family_and_habitat.pdf"), width = 9)

# Depth strata

tmp_df <- summary_by_station_and_family |> 
  mutate(island_exp = paste(location, depth_strata, sep = "-")) |> 
  #mutate(island_exp = if_else(location == "Beveridge", paste(location, exposure, sep = "-"), location)) |> 
  group_by(island_exp, common_family) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Family = ", common_family,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = common_family, tooltip = tooltip))+
  coord_flip()+
  labs(x = "", y = "", fill = "", title = "Fish biomass by location and depth strata")+
  scale_fill_manual(values = rev(fam_palette))+
  ggthemes::theme_hc()+
  guides(fill = guide_legend(nrow = 5))+
  theme(legend.text = element_text(size = 6),
        legend.key.size = unit(.5, "lines"),
        legend.margin=margin(0,0,0,0))

ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_family_and_depth_strata.pdf"), width = 9)
```

## By trophic group

```{r}
#| column: screen-inset-shaded
#| layout-nrow: 1
summary_by_station_and_trophic <- biomass_by_strata |> 
  left_join(taxa_list |> distinct(taxon_valid_name, trophic)) |> 
  left_join(fish_meta |> distinct(ps_station_id, location, habitat, exposure)) |> 
  group_by(location,  habitat, trophic, ps_station_id, depth_strata, diver, exposure) |>
  summarize(gr_m2 = sum(gr_m2)) |> ungroup() 

# exposure

tmp_df <- summary_by_station_and_trophic |> 
  mutate(island_exp = paste(location, exposure, sep = "-")) |> 
  #mutate(island_exp = if_else(location == "Beveridge", paste(location, exposure, sep = "-"), location)) |> 
  group_by(island_exp, trophic) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Trophic group = ", trophic,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = trophic, tooltip = tooltip))+
  coord_flip()+
  labs(x = "", y = expression(Fish~biomass~(g/m^{2})),
       fill = "", title = "Fish biomass by location and exposure")+
  paletteer::scale_fill_paletteer_d("ggthemes::Tableau_10")+
  ggthemes::theme_hc()+
  guides(fill=guide_legend(nrow=2,byrow=TRUE))

ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_trophic_and_exposure.pdf"), width = 9)

# Habitat

tmp_df <- summary_by_station_and_trophic |> 
  mutate(island_exp = paste(location, habitat, sep = "-")) |> 
  group_by(island_exp, trophic) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Trophic group = ", trophic,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = trophic, tooltip = tooltip))+
  coord_flip()+
  labs(x = "", fill = "", y = expression(Fish~biomass~(g/m^{2})),
       title = "Fish biomass by location and habitat")+
  paletteer::scale_fill_paletteer_d("ggthemes::Tableau_10")+
  ggthemes::theme_hc()+
  guides(fill=guide_legend(nrow=2,byrow=TRUE))

ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_trophic_and_habitat.pdf"), width = 9)

# Depth strata

tmp_df <- summary_by_station_and_trophic |> 
  mutate(island_exp = paste(location, depth_strata, sep = "-")) |> 
  #mutate(island_exp = if_else(location == "Beveridge", paste(location, exposure, sep = "-"), location)) |> 
  group_by(island_exp, trophic) |> 
  summarize(gr_m2 = round(mean(gr_m2),2)) |> 
  ungroup()

tmp_plot <- tmp_df |> 
  mutate(tooltip = c(paste0("Trophic group = ", trophic,
                            "\n Biomass = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_col_interactive(aes(x = fct_reorder(island_exp, gr_m2, sum), 
                                    y = gr_m2, 
                                    fill = trophic, tooltip = tooltip))+
  coord_flip()+
  labs(x = "", y = expression(Fish~biomass~(g/m^{2})),
       fill = "", title = "Fish biomass by location and depth strata")+
  paletteer::scale_fill_paletteer_d("ggthemes::Tableau_10")+
  ggthemes::theme_hc()+
  guides(fill=guide_legend(nrow=2, byrow=TRUE))

ggiraph::girafe(ggobj = tmp_plot)

ggsave(plot = tmp_plot, 
       file.path(exp_path, "figures", "uvs_fish_biomass_by_trophic_and_depth_strata.pdf"), width = 9)
```

## By species

```{r}
tmp_plot <- biomass_by_taxa |> 
  mutate(ind_100m2 = 100*ind_m2) |> 
  mutate_if(is.numeric, round, 3) |> 
  mutate(tooltip = c(paste0("Taxa = ", taxon_valid_name,
                            "\n Common family = ", common_family,
                            "\n Frequency (% sites) = ", freq,
                            "\n Abundance (ind/100m2) = ", ind_100m2,
                            "\n Biomass (g/m2) = ", gr_m2))) |> 
  ggplot()+
  ggiraph::geom_point_interactive(aes(x = freq, 
                                      y = ind_100m2, 
                                      size = gr_m2, 
                                      col = trophic, 
                                      tooltip = tooltip))+
  paletteer::scale_colour_paletteer_d("ggthemes::Tableau_10")+
  scale_y_log10()+
  labs(y = "Abundance (Ind x 100m2)", x = "Frequency (% station-strata)", col = "Trophic group", size = "Biomas")+
  ggthemes::theme_hc()+
  theme(legend.title.position = "top", legend.position = "right")

ggiraph::girafe(ggobj = tmp_plot)
```


```{r}
#| column: screen-inset-shaded

biomass_by_taxa_and_island <- biomass_by_strata |> 
  left_join(fish_meta |> 
              distinct(location, ps_station_id)) |> 
  group_by(location, taxon_valid_name) |> 
  summarise(freq = 100*sum(ind_m2 > 0)/n(),
            across(c("ind_m2",  "gr_m2"), mean, na.rm = T)) 

biomass_by_taxa |> 
  left_join(biomass_by_taxa_and_island |> 
              pivot_wider(names_from = location, 
                          values_from = c(freq, ind_m2, gr_m2),
                          names_glue = "{location}.{.value}")) |> 
  rename("Overall.freq" = "freq", "Overall.ind_m2" = "ind_m2", "Overall.gr_m2" = "gr_m2") |> 
  select(trophic, taxon_valid_name, contains("over"),contains("anti"), contains("Beve"), contains("Niu")) |> 
  mutate_if(is.numeric, round, 3) |> 
  gt::gt() |> 
  opt_interactive(use_search = TRUE,
    use_filters = TRUE,
    use_resizers = TRUE,
    use_highlight = TRUE,
    use_compact_mode = TRUE,
    #use_text_wrapping = FALSE,
    use_page_size_select = TRUE) |> 
  #gt::tab_spanner_delim(delim = ".") |> 
  gt::tab_header(title = "Fish abundance (ind/m2), biomass (g/m2), and frequency of observation (% strata)") |> 
  opt_align_table_header(align = "left") |>
  tab_options(heading.padding = px(1))
```

## Community composition

```{r include = T, eval = T}
library(vegan)

gr_m2_data_wide <- biomass_by_strata %>% 
  mutate(strata_id = paste(ps_station_id, depth_strata, diver, sep = "_")) |> 
  select(strata_id, taxon_valid_name, gr_m2) %>% 
  pivot_wider(names_from = taxon_valid_name, values_from = gr_m2) %>% 
  column_to_rownames("strata_id")

gr_m2_dist <- vegan::vegdist(as.matrix(gr_m2_data_wide), 
                      method = "bray") 
```

```{r eval = T, include = T, fig.height=7}
gr_m2_pcoa_c <- vegan::dbrda(gr_m2_dist ~ location + exposure, 
                      data = summary_by_strata,
                      dist = "bray", 
                      add = "lingoes")

gr_m2_pcoa_c_env_fit <- vegan::envfit(gr_m2_pcoa_c, 
                               summary_by_strata %>% 
                                 select(location, exposure))

gr_m2_pcoa_c_spp_fit <- vegan::envfit(gr_m2_pcoa_c, 
                               gr_m2_data_wide)

gr_m2_pcoa_c_spp_scores <- gr_m2_pcoa_c_spp_fit %>% 
  vegan::scores("vectors") %>% 
  as_tibble(rownames = "ps_taxon_code") %>% 
  mutate(r = gr_m2_pcoa_c_spp_fit$vectors$r,
         p = gr_m2_pcoa_c_spp_fit$vectors$pvals) %>% 
  filter(p < 0.05, r > 0.1)

gr_m2_pcoa_c_axis <- BiodiversityR::axis.long(gr_m2_pcoa_c, choices = c(1, 2))

gr_m2_pcoa_c_site_scores <- vegan::scores(gr_m2_pcoa_c)$sites %>% 
  as_tibble(rownames = "strata_id") %>% 
  inner_join(summary_by_strata |>
                 mutate(strata_id = paste(ps_station_id, depth_strata, diver, sep = "_")))

ggplot() +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  geom_point(data = gr_m2_pcoa_c_site_scores,
             aes(x = dbRDA1, y = dbRDA2, col = location)) +
  labs(x = gr_m2_pcoa_c_axis$label[1], y = gr_m2_pcoa_c_axis$label[2])+
  geom_segment(data = gr_m2_pcoa_c_spp_scores %>% 
                 filter(p < 0.05, r > 0.3), 
               aes(x = 0, y = 0, xend = dbRDA1*3, yend = dbRDA2*3, alpha = r), 
               colour = "black", 
               size = 0.2, 
               arrow = arrow(length = unit(0.01, "npc"), 
                             type = 'open', ends = "last"))+
      ggrepel::geom_text_repel(data = gr_m2_pcoa_c_spp_scores %>% 
                                 filter(p < 0.05, r > 0.3), 
                               aes(x=dbRDA1*3, y=dbRDA2*3, label = ps_taxon_code, alpha = r),
                               colour="black",
                               show.legend = F)+ 
      coord_fixed(ratio=1)+
      labs(color = "", alpha = bquote('R'^'2'))+
      ggforce::geom_mark_ellipse(data = gr_m2_pcoa_c_site_scores, 
                                 aes(x=dbRDA1, y = dbRDA2, colour = location, 
                                     fill=after_scale(alpha(colour, 0.01))), 
                                 expand=0, size=0.2, show.legend=FALSE)+
      theme(panel.background = element_blank(),
            panel.border = element_blank(),
            panel.grid = element_blank(),
            axis.line = element_line("gray25"),
            text = element_text(size = 12),
            axis.text = element_text(size = 10, colour = "gray25"),
            axis.title = element_text(size = 12, colour = "gray25"),
            legend.key = element_blank())+
      PristineSeasR::scale_color_pristine_seas(palette = "alternative")+
      scale_alpha(range=c(0.6,1))

ggsave(file.path(exp_path, "figures", "uvs_fish_biomass_pcoa_v2.pdf"), width = 10)
```

```{r}
community_adonis <- vegan::adonis2(gr_m2_dist ~  location + exposure + habitat + depth_strata,
        data = summary_by_strata,
        by = "margin")

broom::tidy(community_adonis) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  gt() |> 
  tab_header(title = "Results of community composition adonis model")
```

```{r}
anova(gr_m2_pcoa_c, 
      perm.max = 500) |> 
  broom::tidy() |> 
  mutate_if(is.numeric, round, 3) %>% 
  gt() |> 
  gt::tab_header(title = "Overall fit of the ordination model")

anova(gr_m2_pcoa_c, 
      by = "axis", 
      perm.max = 500) |> 
  broom::tidy() |> 
  mutate_if(is.numeric, round, 3) %>% 
  gt() |> 
  gt::tab_header(title = "Significance of each axis in the ordination model")

anova(gr_m2_pcoa_c, 
      by = "terms",
      perm.max = 500) |> 
  broom::tidy() |> 
  mutate_if(is.numeric, round, 3) %>% 
  gt() |> 
  gt::tab_header(title = "Significace of each term in the ordination model")
```

## Changes since 2016

```{r}
uvs_meta_2016 <- readxl::read_xls(file.path(exp_path, 
                               "data/secondary/raw/2016-expedition/Niue_benthic_metadata.xls")) |> 
  janitor::clean_names() |> 
  mutate(ps_station_id = paste("NIU_2016_uvs", 
                               formatC(station, width = 2, flag = 0),
                               sep = "_"),
         habitat = str_to_sentence(habitat),
         island = str_to_sentence(reef)) |> 
  select(ps_station_id, everything(), -station, -reef)

fish_obs_2016 <- readxl::read_xlsx(file.path(exp_path, 
                               "data/secondary/raw/2016-expedition/Niue_fish_data_Pristine_Seas.xlsx")) |> 
  janitor::clean_names() |> 
  filter(datatyp == 'QUAN') |> 
  select(station, depth_strata, depth_m, diver, transect, taxon_code = species, n_ind = number, avg_tl_cm = avg, 
         taxon_name = name_fishbase) |> 
  mutate(ps_station_id = paste("NIU_2016_uvs", 
                               formatC(station, width = 2, flag = 0), 
                               sep = "_"),
         depth_strata = str_to_sentence(depth_strata)) |> 
  select(ps_station_id, everything(), -station) |> 
  filter(!is.na(n_ind))

# fish_obs_2016 |> 
#   filter(depth_strata == "Backreef") |> 
#   distinct(ps_station_id, diver, depth_m, transect)
# 
# fish_obs_2016 |> 
#   filter(depth_strata == "Supershallow") |> 
#   distinct(ps_station_id, diver, depth_m, transect)


fish_obs_2016$depth_strata[fish_obs_2016$depth_strata == "Backreef"] <- "Supershallow"

fish_obs_2016 <- fish_obs_2016 |> 
  left_join(taxa_list) |> 
  filter(!is.na(a)) |> 
  mutate(biomass_gr = n_ind*a*(avg_tl_cm)^b,
         ind_m2 = if_else(avg_tl_cm <= 20, n_ind/50, n_ind/100),
         gr_m2 = if_else(avg_tl_cm <= 20, biomass_gr/50, biomass_gr/100)) |> 
  ungroup()

# fish_obs_2016 |> 
#   filter(avg_tl_cm > max_length_tl) |> 
#   mutate(diff = abs(avg_tl_cm - max_length_tl)) |> 
#   arrange(desc(diff))

fish_obs_2016 <- fish_obs_2016 |> 
  mutate(avg_tl_cm = if_else(avg_tl_cm > max_length_tl, max_length_tl, avg_tl_cm))

fish_obs_2016 <- fish_obs_2016 |> 
  select(ps_station_id, diver, transect, taxon_code, taxon_valid_name,  
         avg_tl_cm, n_ind, ind_m2,biomass_gr, gr_m2, everything()) 

write_csv(fish_obs_2016,
          file.path(exp_path, "data/primary/processed/NIU_2016_uvs_fish_obs.csv"))
```

```{r}
biomass_2016 <- fish_obs_2016 |> 
  group_by(ps_station_id, diver, depth_strata, transect, taxon_valid_name) |> 
  summarise(ind_m2 = sum(ind_m2),
            gr_m2 = sum(gr_m2)) |> 
  ungroup() |> 
  pivot_wider(names_from = taxon_valid_name, 
              values_from = c(ind_m2, gr_m2), 
              values_fill = 0, 
              names_sep = "-") |> 
  pivot_longer(cols = !c(ps_station_id, diver, depth_strata, transect),
               names_to = c("variable","taxon_valid_name"), 
               names_sep = "-",
               values_to = "value") |> 
  pivot_wider(names_from = variable, values_from = value) |> 
  mutate_if(is.numeric, round, 4) |> 
  left_join(uvs_meta_2016 |> 
              select(island, ps_station_id, habitat)) |> 
  left_join(taxa_list |> 
              select(taxon_valid_name, taxon_valid_name, common_family, trophic)) |> 
  mutate(year = 2016) |> 
  select(year, everything()) |> 
  group_by(year, location = island, habitat, ps_station_id, diver,
           depth_strata, taxon_valid_name, transect, common_family, trophic) |>
  summarize(ind_m2 = sum(ind_m2),
            gr_m2 = sum(gr_m2)) |> 
  ungroup()

biomass_by_transect_2016 <- biomass_2016 |> 
  group_by(year, location, habitat, ps_station_id, diver, depth_strata, transect) |>
  summarize(n_taxa = n_distinct(taxon_valid_name[ind_m2 > 0]),
            ind_m2 = sum(ind_m2),
            gr_m2 = sum(gr_m2)) |> 
  ungroup() 

biomass_by_strata_2016 <- biomass_by_transect_2016 |> 
  group_by(year, location, habitat, ps_station_id, diver, depth_strata) |>
  summarize(n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  ungroup() 

biomass_by_station_2016 <- biomass_by_transect_2016 |> 
  group_by(year, location, habitat, ps_station_id) |>
  summarize(n_taxa = mean(n_taxa),
            ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  ungroup() |> 
  arrange(ps_station_id) |> 
  mutate_if(is.numeric, round, 4)

biomass_by_taxa_and_strata_2016 <- biomass_2016 |> 
  group_by(year, location, habitat, ps_station_id, diver, depth_strata, 
           taxon_valid_name, common_family, trophic) |> 
  summarize(ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  ungroup() 

biomass_by_taxa_and_station_2016 <- biomass_by_taxa_and_strata_2016 |> 
  group_by(year, location, habitat, ps_station_id, taxon_valid_name, common_family, trophic) |> 
  summarize(ind_m2 = mean(ind_m2),
            gr_m2 = mean(gr_m2)) |> 
  ungroup()
```

```{r}
biomass_by_strata_combined <- biomass_by_strata_2016 |> 
  bind_rows(summary_by_strata) |> 
  select(-exposure) |> 
  replace_na(list(year = 2023))

biomass_by_taxa_and_strata_combined <- biomass_by_taxa_and_strata_2016 |> 
  bind_rows(biomass_by_strata |> 
              left_join(taxa_list |> distinct(taxon_valid_name, trophic)) |> 
              left_join(fish_meta |> distinct(ps_station_id, location, habitat)))|> 
  replace_na(list(year = 2023))
```

```{r}
biomass_by_strata_combined |> 
  filter(location != "Antiope") |> 
  group_by(year, location, depth_strata) |> 
  summarize(gr_m2 = round(mean(gr_m2), 2)) |> 
  pivot_wider(names_from = year, values_from = gr_m2) |> 
    ungroup() |> 
  gt(groupname_col = "location", rowname_col = "depth_strata") |> 
  tab_stubhead(label = "Location/Strata") |> 
  gt::tab_header(title = "Changes in fish biomass by location and depth strata (2016-2023)") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(style = cell_text(align = "left", indent = px(20)),
    locations = cells_stub())
```

```{r}
biomass_by_strata_combined |> 
  filter(location != "Antiope") |> 
  ggplot()+
  geom_boxplot(aes(x = depth_strata, y = gr_m2, col = factor(year)))+
  facet_wrap("location")+
  scale_fill_brewer(palette="Set1")+
  labs(title = 'Changes in fish biomass between 2016 an 2023',
       y = expression(Fish~biomass~(g/m^{2})),
       x = "", fill = "", col = "")+
  paletteer::scale_color_paletteer_d(palette = "ggthemes::Superfishel_Stone")+
  scale_y_continuous(limits = c(0,700))+
  ggthemes::theme_hc()

ggsave(file.path(exp_path, "figures/fish_biomass_2016_2023_boxplot_no_outliers.pdf"))
```

```{r }
#| column: page
#| layout-nrow: 1
tmp <- biomass_by_taxa_and_strata_combined |> 
  filter(location == "Niue") |> 
  group_by(year, location, habitat, ps_station_id, diver, depth_strata, trophic) |>
  summarize(gr_m2 = sum(gr_m2, na.rm = T)) |> 
  ungroup() |> 
  group_by(year, location, depth_strata, trophic) |> 
  summarize(gr_m2 = round(mean(gr_m2, na.rm = T),2)) |> 
  mutate(year = factor(year)) |> 
  ggplot(aes(x = year, y = gr_m2, fill = trophic))+
  ggiraph::geom_col_interactive(aes(tooltip = gr_m2))+
  facet_wrap( vars(depth_strata))+
  paletteer::scale_fill_paletteer_d(palette = "ggthemes::few_Light", guide = guide_legend(nrow = 2))+
  labs(fill = "", title = 'Fish biomass in Niue (gr/m<sup>2</sup>)')+
  #bbplot::bbc_style()+
  paletteer::scale_fill_paletteer_d("ggthemes::Tableau_10")+
  ggthemes::theme_hc()+
  theme(legend.position = "bottom", 
        plot.title = element_markdown())

ggiraph::girafe(ggobj = tmp)

ggsave(plot = tmp, 
       file.path(exp_path, "figures/fish_biomass_2016_2023_Niue.pdf"), width = 10)

tmp <- biomass_by_taxa_and_strata_combined |> 
  filter(location == "Beveridge") |> 
  group_by(year, location, habitat, ps_station_id, diver, depth_strata, trophic) |>
  summarize(gr_m2 = sum(gr_m2, na.rm = T)) |> 
  ungroup() |> 
  group_by(year, location, depth_strata, trophic) |> 
  summarize(gr_m2 = round(mean(gr_m2, na.rm = T),2)) |> 
  mutate(year = factor(year)) |> 
  ggplot(aes(x = year, y = gr_m2, fill = trophic))+
  ggiraph::geom_col_interactive(aes(tooltip = gr_m2))+
  facet_wrap( vars(depth_strata))+
  paletteer::scale_fill_paletteer_d(palette = "ggthemes::few_Light", guide = guide_legend(nrow = 2))+
  labs(fill = "", title = 'Fish biomass in Beveridge (gr/m<sup>2</sup>)')+
  #bbplot::bbc_style()+
  ggthemes::theme_hc()+
  paletteer::scale_fill_paletteer_d("ggthemes::Tableau_10")+
  theme(legend.position = "bottom", 
        plot.title = element_markdown())

ggiraph::girafe(ggobj = tmp)

ggsave(plot = tmp, 
       filename = file.path(exp_path, "figures/fish_biomass_2016_2023_Beveridge.pdf"), width = 10)
```

```{r fig.width=15, fig.height = 5}
#| column: page
biomass_by_strata_combined$year <- as.factor(biomass_by_strata_combined$year)

(tmp <- ggstatsplot::grouped_ggbetweenstats(data = biomass_by_strata_combined |> 
                                      filter(location != "Antiope"), 
                       x = year, 
                       y = gr_m2,
                       grouping.var = location,
                       type = "nonparametric", p.adjust.method = "none",
                       annotation.args = list(title = "Changes in fish biomass by location"),
                       plotgrid.args = list(nrow = 1)))

ggsave(plot = tmp, 
       file.path(exp_path, "figures/fish_biomass_2016_2023_Beveridge_Niue.pdf"), width = 14)
```

```{r}
comparisons_adonis <- vegan::adonis2(biomass_by_strata_combined %>% 
                                          select(gr_m2) ~  depth_strata + habitat  + location + year, 
                                        data = biomass_by_strata_combined,
                                        permutations = 1000,
                                        by = "margin",
                                        method = "euclidean")

broom::tidy(comparisons_adonis) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  gt() |> 
  tab_header(title = "Results of Adonis model for univariate analysis of fish diversity")
```

```{r}
# biomass_by_taxa_and_strata_combined |> 
#   select(-exposure) |> 
#   arrange(year, ps_site_id) |> 
#   write_csv(file.path(exp_path, "data/primary/output/biomass_by_taxa_and_strata_2013_2016_combined.csv"))
# 
# biomass_by_strata_combined |> 
#   arrange(year, ps_site_id) |> 
#   write_csv(file.path(exp_path, "data/primary/output/biomass_by_strata_2013_2016_combined.csv"))
```

```{r fig.width=15}
#| column: page
ggstatsplot::grouped_ggbetweenstats(data = biomass_by_strata_combined |> 
                                      filter(location == "Beveridge"), 
                                    x = year, 
                                    y = gr_m2,
                                    grouping.var = depth_strata,
                                    type = "nonparametric", 
                                    p.adjust.method = "none", 
                                    plotgrid.args = list(nrow = 1),
                                    annotation.args = list(title = "Changes in fish biomass in Beveridge reef by depth strata"))

ggsave(file.path(exp_path, "figures/fish_biomass_2016_2023_Beveridge.pdf"))
```


